1
Testov4/myAnimeListProject pull request #1
Opened 2023-08-27 20:25 UTC by Testov4

маленький пр реквест для моего друга тимофея

2023-08-28 20:08 UTC, fartako requested changes

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/ApiListenerApplication.java
> +public class ApiListenerApplication {
название говно

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/ApiListenerApplication.java
> +		SpringApplication.run(ApiListenerApplication.class, args);
опять бля отступы

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/configuration/KafkaConsumerConfig.java
> +public class KafkaConsumerConfig {
объедени все кафка конфиги в один

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/configuration/KafkaTopicConfig.java
> +public class KafkaTopicConfig {
этот класс вообще нахуй нужен

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/kafka/consumer/AnimeSearchConsumer.java
> +@KafkaListener(topics = "${spring.kafka.topic.name.consume}", groupId = "groupId")
и че это за группа

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/kafka/consumer/AnimeSearchConsumer.java
> +@KafkaListener(topics = "${spring.kafka.topic.name.consume}", groupId = "groupId")
и че это за название топика

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/kafka/consumer/AnimeSearchConsumer.java
> +    void listener(@Payload String data, @Header(KafkaHeaders.RECEIVED_KEY) String key) throws JsonProcessingException {
какой нах листенер

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/kafka/consumer/AnimeSearchConsumer.java
> +    void listener(@Payload String data, @Header(KafkaHeaders.RECEIVED_KEY) String key) throws JsonProcessingException {
вот ты пока этот ебучий JsonProcessingException прокидывал по всей цепочке, у тебя не возникло ощущения что ты кал пишешь какой-то? опять таки прочитай про виды исключений

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/kafka/consumer/AnimeSearchConsumer.java
> +        AnimeSearchRequest request = deserializerService.convertToAnimeSearchRequest(data);
почему конверт, десериалазайзер десериализует

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/kafka/consumer/AnimeSearchConsumer.java
> +        log.info("Data serialized: {}", request);
стерилайзд

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/kafka/consumer/AnimeSearchConsumer.java
> +        List<Anime> animeList = animeService.findAnimeByParameters(request);
почему файнд, где искать собрался?

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/kafka/consumer/AnimeSearchConsumer.java
> +        log.info("List from API received: {}", Arrays.toString(animeList.toArray()));
а в чем была проблема просто лист ему дать, че за бубны

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/kafka/consumer/AnimeSearchConsumer.java
> +        log.info("Message sent: {}", Arrays.toString(animeList.toArray()));
сейм

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/model/Anime.java
> +@JsonIgnoreProperties(ignoreUnknown=true)
такие вещи должны лежать в отдельном обжект маппер конфиге

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/model/Anime.java
> +    private Integer mal_id;
ебать это что плюсы какой нах снейк кейс

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/model/Anime.java
> +    private HashMap<String, HashMap<String, String>> images;
за такое на районе пиздят

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/model/Anime.java
> +    private String title_english;
ебать это что плюсы какой нах снейк кейс

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/model/Anime.java
> +    private String title_japanese;
ебать это что плюсы какой нах снейк кейс

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/model/Anime.java
> +    private List<String> title_synonyms;
ебать это что плюсы какой нах снейк кейс

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/model/AnimeListWrapper.java
> +    List<Anime> data;
и где модификатор доступа

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/model/AnimeListWrapper.java
> +@JsonIgnoreProperties(ignoreUnknown=true)
убрать

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/model/AnimeSearchRequest.java
> +@JsonIgnoreProperties(ignoreUnknown=true)
убрать

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/model/AnimeListWrapper.java
> +    List<Anime> data;
этот враппер вообще точно нужен?

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/model/Genre.java
> +
и где модификаторы доступа

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/model/Genre.java
> +@JsonIgnoreProperties(ignoreUnknown=true)
убрать

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/model/Anime.java
> +    private List<Studio> studios;
зачем пробелов наставил

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/model/AnimeSearchRequest.java
> +
и где модификаторы доступа

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/model/Studio.java
> +
и где модификаторы доступа

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/model/Studio.java
> +    Integer mal_id;
какой нах снейк кейс

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/service/AnimeService.java
> +    List<Anime> findAnimeByParameters(AnimeSearchRequest animeSearchRequest) throws JsonProcessingException;
убрать эксепшны

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/service/AnimeService.java
> +    List<Anime> findAnimeByParameters(AnimeSearchRequest animeSearchRequest) throws JsonProcessingException;
переименовать методы

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/service/DeserializerService.java
> +    AnimeSearchRequest convertToAnimeSearchRequest(String json) throws JsonProcessingException;
переименовать метод

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/AnimeServiceImpl.java
> +    private final String url = "https://api.jikan.moe/v4/anime";
а если я захочу иметь возможность поднимать сервак с какой хочу апишкой то че делать будешь

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/AnimeServiceImpl.java
> +    final ObjectMapper mapper = new ObjectMapper();
обжект маппер должен быть бином со своим конфигом

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/AnimeServiceImpl.java
> +        return searchUrl.toString();
пиздец

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/AnimeServiceImpl.java
> +            urlBuilder.append('&').append(paramName).append('=').append(paramValue);
пиздец

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/AnimeServiceImpl.java
> +            .ifPresent(value -> urlBuilder.append('&').append(paramName).append('=').append(value));
пиздец

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/AnimeServiceImpl.java
> +            .append("?");
пиздец

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/AnimeServiceImpl.java
> +        return mapper.readValue(json, AnimeWrapper.class).getData();
пиздец

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/AnimeServiceImpl.java
> +        return mapper.readValue(json, AnimeListWrapper.class).getData();
пиздец

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/AnimeServiceImpl.java
> +        return jsonUrlToAnimeObject("/" + id);
пиздец

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/DeserializerServiceImpl.java
> +    final ObjectMapper mapper = new ObjectMapper();
сейм

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/DeserializerServiceImpl.java
> +    public AnimeSearchRequest convertToAnimeSearchRequest(String json) throws JsonProcessingException {
переименовать

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/DeserializerServiceImpl.java
> +    public AnimeSearchRequest convertToAnimeSearchRequest(String json) throws JsonProcessingException {
про исключения уже писал

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/KafkaServiceImpl.java
> +            .setHeader(KafkaHeaders.KEY, key)
а ключ зачем

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/KafkaServiceImpl.java
> +        log.info("Message sent: {}", data.toString());
а если не сент нихуя?

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/KafkaServiceImpl.java
> +        log.info("Message sent: {}", data.toString());
зачем ту стринг

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/KafkaServiceImpl.java
> +            .setHeader(KafkaHeaders.TOPIC, topicName + "-list")
дефайни сразу топики нормально, че за костыли

2023-08-28 20:08 UTC, fartako commented on src/main/resources/application.properties
> +server.port=8080
а если занят будет?

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/AnimeServiceImpl.java
> +        addToUrlIfNonEmptyList(searchUrl, "producers", animeSearchRequest.getProducers());
пиздец

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/AnimeServiceImpl.java
> +        addToUrlIfNonEmptyList(searchUrl, "genres", animeSearchRequest.getGenres());
пиздец

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/AnimeServiceImpl.java
> +        addToUrlIfPresent(searchUrl, "type", animeSearchRequest.getType());
пиздец

2023-08-28 20:08 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/AnimeServiceImpl.java
> +        addToUrlIfPresent(searchUrl, "q", animeSearchRequest.getTitle());
пиздец

2023-08-28 21:05 UTC, Testov4 commented on src/main/java/anilist/apilistener/kafka/consumer/AnimeSearchConsumer.java
> +@KafkaListener(topics = "${spring.kafka.topic.name.consume}", groupId = "groupId")
вроде поправил на нормальную

2023-08-28 21:09 UTC, Testov4 commented on src/main/java/anilist/apilistener/kafka/consumer/AnimeSearchConsumer.java
> +    void listener(@Payload String data, @Header(KafkaHeaders.RECEIVED_KEY) String key) throws JsonProcessingException {
changed

2023-08-29 16:20 UTC, Testov4 commented on src/main/java/anilist/apilistener/model/AnimeListWrapper.java
> +    List<Anime> data;
ne nuzhen

2023-08-29 21:20 UTC, Testov4 commented on src/main/java/anilist/apilistener/service/implementation/AnimeServiceImpl.java
> +    private final String url = "https://api.jikan.moe/v4/anime";
changed

2023-08-31 13:18 UTC, Testov4 commented on src/main/java/anilist/apilistener/kafka/consumer/AnimeSearchConsumer.java
> +    void listener(@Payload String data, @Header(KafkaHeaders.RECEIVED_KEY) String key) throws JsonProcessingException {
ну я вроде бы захендлил, я не уверен(

2023-08-31 15:52 UTC, closed without merging