Dev
Testov4/myAnimeListProject pull request #2
Opened 2023-08-31 15:53 UTC by Testov4

2

2023-09-02 10:45 UTC, fartako requested changes

2023-09-02 10:45 UTC, fartako commented on src/main/java/anilist/apilistener/AnimeApiRequestApplication.java
> +package anilist.apilistener;
название кал

2023-09-02 10:45 UTC, fartako commented on src/main/java/anilist/apilistener/AnimeApiRequestApplication.java
> +		SpringApplication.run(AnimeApiRequestApplication.class, args);
заебал

2023-09-02 10:45 UTC, fartako commented on src/main/java/anilist/apilistener/kafka/consumer/AnimeSearchConsumer.java
> +    void listenAnimeSearchRequest(String data) throws JsonProcessingException {
прочитай про исключения еще раз пишу

2023-09-02 10:45 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/AnimeServiceImpl.java
> +
лмао

2023-09-02 10:45 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/AnimeServiceImpl.java
> +
ты реально думаешь что в каждом приложении где есть обращение по апихам люди пишут такие велосипеды и ничего проще до сих пор не придумали?

2023-09-02 10:45 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/AnimeServiceImpl.java
> +        return restTemplate.getForObject(buildSearchUrl(animeSearchRequest), String.class);
в 21 веке так уже не делают

2023-09-02 10:45 UTC, fartako commented on src/main/java/anilist/apilistener/model/Anime.java
> +    private HashMap<String, Image> images;
на районе за такое пиздят

2023-09-02 10:45 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/AnimeServiceImpl.java
> +
и это ты только по одному урлу обращаешься, а че будешь делать если нужно будет 50 разных вызовов в разные места делать

2023-09-02 10:45 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/DeserializerServiceImpl.java
> +            throw new RuntimeException(e);
а схуяли рантайм

2023-09-02 10:45 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/DeserializerServiceImpl.java
> +                return List.of();
и че отправить пустой лист это типа ожидаемым ответом у тебя будет?

2023-09-02 10:45 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/DeserializerServiceImpl.java
> +                    });
можно лучше сделать

2023-09-02 10:45 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/KafkaServiceImpl.java
> +    @Value("${spring.kafka.topic.name.produce}")
по поводу всех этих аннотаций которые ты расскидал по классам. Если у тя приложуха станет большой и тебе нужно будет поменять адрес проперти с условного topic.name.produce на topic.nigger.name.produce, ты будешь по всем классам потом лазить исправлять это?

2023-09-02 10:45 UTC, fartako commented on src/main/java/anilist/apilistener/kafka/consumer/AnimeSearchConsumer.java
> +        String animeListJson = animeService.requestAnimeListByParameters(request);
это плохо

2023-09-02 10:45 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/DeserializerServiceImpl.java
> +            return List.of();
сейм

2023-09-02 10:45 UTC, fartako commented on src/main/java/anilist/apilistener/service/implementation/DeserializerServiceImpl.java
> +            log.warn("Failed using mapper to read JSON: {}", e);
почему warn

2023-09-02 10:45 UTC, fartako commented on src/main/resources/application.properties
> +spring.kafka.topic.name.consume=anime-api-request
а если нужно поменять будет?

2023-09-02 10:45 UTC, fartako commented on src/main/resources/application.properties
> +spring.kafka.topic.name.produce=anime-api-response
сейм

2023-09-02 10:45 UTC, fartako commented on src/main/resources/application.properties
> +spring.kafka.consumer.group-id=anime-api-service
сейм

2023-09-02 18:09 UTC, Testov4 commented on src/main/java/anilist/apilistener/service/implementation/AnimeServiceImpl.java
> +
вроде поправил, хз

2023-09-03 11:38 UTC, Testov4 commented on src/main/java/anilist/apilistener/service/implementation/KafkaServiceImpl.java
> +    @Value("${spring.kafka.topic.name.produce}")
вроде вкинул в конфиг чисто

2023-09-03 16:02 UTC, closed without merging